name: Terraform Lint, Security, Plan, Policy & Cost, OPA policies

on: [push]

jobs:
  terraform-checks:
    name: Terraform Checks
    runs-on: ubuntu-latest

    steps:
      # ----- Checkout -----
      - name: Checkout code
        uses: actions/checkout@v4
      
      # ----- AWS -----
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      # ----- Terraform Setup -----
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.2.0

      # ----- Linting -----
      - name: Install TFLint
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

      - name: Run TFLint
        run: tflint --init && tflint --recursive

      # ----- Security -----
      - name: Run Trivy scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: config
          hide-progress: true
          output: trivy.txt

      - name: Publish Trivy Output to Summary
        run: |
          if [[ -s trivy.txt ]]; then
            {
              echo "### Security Output"
              echo "<details><summary>Click to expand</summary>"
              echo ""
              echo '```terraform'
              cat trivy.txt
              echo '```'
              echo "</details>"
            } >> $GITHUB_STEP_SUMMARY
          fi

      # ----- Terraform Init & Plan -----
      - name: Terraform Init
        run: cd ./terraform && terraform init

      - name: Terraform Plan
        run: cd ./terraform && terraform plan -out=tfplan.binary -no-color

      - name: Save Terraform Plan Output
        run: cd ./terraform && terraform show -json tfplan.binary > tfplan.json

      # ----- Infracost Setup -----
      - name: Setup Infracost
        uses: infracost/actions/setup@v2
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}

      - name: Generate Infracost Cost Estimate
        run: |
          infracost breakdown \
            --path=. \
            --format=json \
            --out-file=/tmp/infracost.json

      # ----- OPA Policy Check -----
      - name: Install OPA & Conftest
        run: |
          # Install OPA
          curl -L -o opa https://openpolicyagent.org/downloads/latest/opa_linux_amd64
          chmod +x opa && sudo mv opa /usr/local/bin/opa
          
          # Install Conftest
          CONTEST_VERSION=$(curl -s https://api.github.com/repos/open-policy-agent/conftest/releases/latest | grep tag_name | cut -d '"' -f 4)
          curl -L -o conftest.tar.gz "https://github.com/open-policy-agent/conftest/releases/download/${CONTEST_VERSION}/conftest_${CONTEST_VERSION#v}_Linux_x86_64.tar.gz"
          tar xzf conftest.tar.gz
          sudo mv conftest /usr/local/bin/conftest
          conftest --version
          opa version

      - name: Run OPA Policy Checks
        id: evaluate_policies
        run: |
          # run fresh plan
          cd ./terraform
          terraform init && terraform plan -out=tfplan.binary -no-color
          terraform show -json tfplan.binary > tfplan.json
          conftest test tfplan.json --policy ./policies || echo "OPA Policy Violations Found"
          echo "::set-output name=exit_code::$EXIT_CODE"

      - name: Comment OPA results
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const result = fs.readFileSync('conftest_output.txt', 'utf8');
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🛑 **OPA Policy Violations**\n\n\`\`\`\n${result}\n\`\`\``
            })

      - name: OPA Rules Evaluation Failed
        if: ${{ steps.evaluate_policies.outputs.exit_code != 0 }}
        run: |
          echo "The terraform resources you are deploying on the AWS Account are not complying with the defined standard. Please check the "Evaluate Rego Policies" to find the configuration which is not compliant and fix the code. "
          exit 1

          # - name: Terraform Apply
          #   if: steps.evaluate_policies.outputs.exit_code == 0
          #   run: terraform apply -auto-approve
