name: Terraform Lint, Security, Plan & Cost

on:
  pull_request:
    paths:
      - '**.tf'
      - '.github/workflows/terraform-lint-security-plan-cost.yml'

jobs:
  terraform-checks:
    name: Terraform Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.2.0

      # ----- Linting -----
      - name: Install TFLint
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

      - name: Run TFLint
        run: tflint --init && tflint --recursive

      # ----- Security -----
      - name: Install tfsec
        run: |
          curl -s https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash

      - name: Run tfsec
        run: tfsec .

      # ----- Terraform Init & Plan -----
      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -out=tfplan.binary -no-color

      - name: Save Terraform Plan Output
        run: terraform show -no-color tfplan.binary > tfplan.txt

      # ----- Infracost Setup -----
      - name: Setup Infracost
        uses: infracost/actions/setup@v2
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}

      - name: Generate Infracost Cost Estimate
        run: |
          infracost breakdown \
            --path=. \
            --format=json \
            --out-file=/tmp/infracost.json